# Generated by Django 4.1 on 2022-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolment", "0003_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
