# Generated by Django 4.1 on 2022-09-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolment", "0004_class_name"),
    ]

    operations = [
        migrations.RenameModel(old_name="Class", new_name="Subject",),
    ]
